# Generated by Django 2.0.9 on 2018-11-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0002_user_profiles")]

    operations = [
        migrations.AddField(
            model_name="releasegroup", name="cover_art_url", field=models.URLField(blank=True)
        )
    ]
