# Generated by Django 2.0.9 on 2018-11-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0003_cover_art_url")]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="disambiguation",
            field=models.CharField(blank=True, max_length=512),
        )
    ]
