# Generated by Django 2.0.9 on 2018-11-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='last_check_for_releases',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releasegroup',
            name='last_check_for_cover_art',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
