# Generated by Django 2.0.9 on 2018-11-25 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_backoff_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.FloatField(blank=True, null=True)),
                ('from_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_artists', to='app.Artist')),
                ('to_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_artists', to='app.Artist')),
            ],
            options={
                'verbose_name': 'Artist Similarity',
                'verbose_name_plural': 'Artist Similarities',
                'ordering': ('-match',),
            },
        ),
        migrations.AlterField(
            model_name='userartist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='similar_artists',
            field=models.ManyToManyField(related_name='related_to', through='app.ArtistSimilarity', to='app.Artist'),
        ),
    ]
