# Generated by Django 2.0.9 on 2018-12-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_safari',
            field=models.BooleanField(default=False),
        ),
    ]
